apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-vite-blog-backend
  namespace: golang-vite-blog
  labels:
    app: golang-vite-blog-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-vite-blog-backend
  template:
    metadata:
      labels:
        app: golang-vite-blog-backend
    spec:
      containers:
        - name: golang-vite-blog-backend
          image: ideavn/golang-vite-blog-backend:{latest}
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: golang-vite-blog-backend-env
          resources:
            limits:
              cpu: 80m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi

---
apiVersion: v1
kind: Service
metadata:
  name: golang-vite-blog-backend-service
  namespace: golang-vite-blog
spec:
  selector:
    app: golang-vite-blog-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30150

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-vite-blog-backend-ingress
  namespace: golang-vite-blog
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: dongtran-backend.sequential-ci.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: golang-vite-blog-backend-service
            port:
              number: 4000
