apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-vite-blog-frontend
  namespace: golang-vite-blog
  labels:
    app: golang-vite-blog-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golang-vite-blog-frontend
  template:
    metadata:
      labels:
        app: golang-vite-blog-frontend
    spec:
      containers:
        - name: golang-vite-blog-frontend
          image: ideavn/golang-vite-blog-frontend:{latest}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: golang-vite-blog-frontend-env
          resources:
            limits:
              cpu: 80m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi

---
apiVersion: v1
kind: Service
metadata:
  name: golang-vite-blog-frontend-service
  namespace: golang-vite-blog
spec:
  selector:
    app: golang-vite-blog-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30151

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-vite-blog-ingress
  namespace: golang-vite-blog
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: dongtran.sequential-ci.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: golang-vite-blog-frontend-service
            port:
              number: 3000
