apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: golang-vite-blog-frontend
  namespace: golang-vite-blog
  labels:
    app: golang-vite-blog-frontend
spec:
  serviceName: golang-vite-blog-frontend
  replicas: 2
  selector:
    matchLabels:
      app: golang-vite-blog-frontend
  template:
    metadata:
      labels:
        app: golang-vite-blog-frontend
    spec:
      containers:
        - name: golang-vite-blog-frontend
          image: ideavn/golang-vite-blog-frontend:{latest}
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: golang-vite-blog-frontend-service
  namespace: golang-vite-blog
spec:
  selector:
    app: golang-vite-blog-frontend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-vite-blog-ingress
  namespace: golang-vite-blog
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: dtur.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: golang-vite-blog-frontend-service
            port:
              number: 3000
