apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: database-change-monitoring
  name: configmap-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: database-change-monitoring
  name: configmap-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: database-change-monitoring
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io